name: youtube_kbd_nav
description: >-
  A keyboard navigation extension for Youtube, enabling more accessibility
  shortcuts on the platform.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.2

dev_dependencies:
  mockito: ^4.1.1
  test: ^1.15.3