name: youtube_kbd_nav
description: >-
  A keyboard navigation extension for Youtube, enabling more accessibility 
  shortcuts on the platform.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  html: ^0.14.0+3
  meta: ^1.2.2
  webext: ^0.1.3

dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0
  test: ^1.15.3
  webdev: ^2.3.0
  webextdev: ^0.1.3