name: youtube_kbd_nav
description: >-
  A keyboard navigation extension for Youtube, enabling more accessibility
  shortcuts on the platform.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.2

dev_dependencies:
  test: ^1.15.3