name: youtube_kbd_nav
description: >-
  A keyboard navigation extension for Youtube, enabling more accessibility 
  shortcuts on the platform.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.2
  mockito: ^4.1.1
  webext: ^0.1.3

dev_dependencies:
  build_runner: ^1.10.1
  build_web_compilers: ^2.11.0
  test: ^1.15.3
  webdev: ^2.5.9
  webextdev: ^0.1.3